version: "3"
services:

  frontend:
    image: 99bugs/nubg:develop
    container_name: 'nubg-frontend'
    ports:
      - 80
    restart: always
    environment:
      - VIRTUAL_HOST=battle.nubg.world
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=battle.nubg.world
      - LETSENCRYPT_EMAIL=sille.vanlandschoot@vives.be
      - PUBLIC=battle.nubg.world
    ports:
      - '8050:80'
